
#define Renk_Gri 			0xAFAFAFAA
#define Renk_Yesil 			0x33AA33AA
#define Renk_Kirmizi 		0xAA3333AA
#define Renk_AcikKirmizi	0xFF0000FF
#define Renk_AltinSarisi 	0xB8860BAA
#define Renk_Mavi 			0x33CCFFAA
#define Renk_Mor 			0x800080FF
#define Renk_Beyaz 			0xFFFFFFAA
#define Renk_Sari 			0xFFFF00AA
#define Renk_Siyah 			0x000000AA
#define Renk_Turuncu		0xFF8000FF
#define Renk_Pembe 			0xFFC0CBAA

#define DiRenk_Kirmizi 		"{FF0000}"
#define DiRenk_Yesil 		"{6EF83C}"
#define DiRenk_Beyaz 		"{FFFFFF}"
#define DiRenk_Gri			"{C3C3C3}"
#define DiRenk_Pembe 		"{FF00EA}"
#define DiRenk_Siyah		"{0E0101}"
#define DiRenk_Mavi			"{0049FF}"
#define DiRenk_Sari			"{F3FF02}"
#define DiRenk_Turuncu		"{FFAF00}"